"""empty message

Revision ID: 5aeb14e5225f
Revises: 
Create Date: 2017-04-14 14:46:04.435034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aeb14e5225f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writeups',
    sa.Column('idwriteup', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('task', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('ctftime_link', sa.String(length=255), nullable=True),
    sa.Column('original_writeup', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idwriteup')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writeups')
    # ### end Alembic commands ###
